[package]
name = "yaml"
version = "0.1.0"
edition = "2021"

[dependencies]
cipher = { path = "../cipher" }

serde_yaml = "0.9.29"
thiserror = "1.0.52"
rand_chacha = "0.3.1"
rand = "0.8.5"

once_cell = "1.19.0"
